# Pandas

Its a very powerful open soruce library that is extensively used in data accessing and manipulation. It's widely used accross Data science course field as well. It offers below -

## Why We Need Pandas

1. Data Manipulation: Pandas makes it easy to clean, transform, and analyze data. It provides functions for filtering, selecting, and combining data in various ways, enabling users to prepare data for analysis quickly.

2. Handling Diverse Data: Pandas can handle a wide variety of data types, including tabular data, time series, and matrix data. It can read and write data from and to many sources like CSV, Excel files, SQL databases, and more.

3. Ease of Use: With its DataFrame and Series data structures, Pandas allows for intuitive and efficient data manipulation. This simplicity makes data analysis tasks more straightforward than using Pythonâ€™s built-in data structures.

4. Integration with Other Libraries: Pandas integrates well with other data science and machine learning libraries in the Python ecosystem, such as NumPy, SciPy, Matplotlib, and scikit-learn, allowing for a seamless data analysis and modeling workflow.

# Installing Pandas

In [ ]:
!pip install pandas

In [ ]:
import pandas as pd

In [ ]:
pd.__version__

In [ ]:
import numpy as np
np.__version__

# Creating Dataframes

1. What is a dataframe?
2. How is it related to other data storage options?

A DataFrame is a fundamental data structure in the Python programming library pandas, which is designed for data manipulation and analysis. Essentially, a DataFrame represents a table of data with rows and columns, similar to a spreadsheet, a SQL table, or data in a CSV file. Each column in a DataFrame can hold data of a single data type, but different columns can hold different types of data (e.g., integers, floats, strings, Python objects, etc.).

In [ ]:
# Creating using Dictionaries of lists
data = {'column A':[3,4,5,6],
       'column B': [5,8,9,0]}

df = pd.DataFrame(data)
df

# Columns --> variables, features, dimensions
# Rows -->  index_values, observations, records, values, data points

In [ ]:
# List of Dictionaries
data = [
    {'Column1': 1, 'Column2': 'A', 'Column3':"Balaji"},
    {'Column1': 2, 'Column2': 'B'},
    {'Column1': 3, 'Column2': 'C'}
]
df = pd.DataFrame(data)
df

In [ ]:
type(pd.Series([1, 2, 3]))

In [ ]:
data = {
    'Column1': pd.Series([1, 2, 3]),
    'Column2': pd.Series(['A', 'B'])
}
df = pd.DataFrame(data)
df

In [ ]:
data = [
    ['1', 'A'],
    [2, 'B'],
    [3, 'C']
]
columns = ['balaji1', 'balaji2']
df = pd.DataFrame(data, columns=columns)
df

In [ ]:
df.dtypes

In [ ]:
df = pd.DataFrame({'float': [1.0],
                   'int': [1],
                   'datetime': [pd.Timestamp('20240223')],
                   'string': ['BALAJI']})

df

In [ ]:
df.dtypes

In [ ]:
# Enforcing Datatypes while creating.

# Creating using Dictionaries
data = {'column A':['1',4,5,6],
       'column B': [5,8,9,0]}
df = pd.DataFrame(data=data, dtype=np.int8)
df

In [ ]:
df.dtypes

In [ ]:
data = {'column A':[3,4,5,6],
       'column B': [5,8,9,0]}

df = pd.DataFrame(data)
df['column B']

In [ ]:
type(df['column B'])

In [ ]:
np.array(df['column B'])

In [ ]:
array = np.array(df['column A'])
array = array+2
array

In [ ]:
df

In [ ]:
# Modifying elements of columns
df['column A'] = array
df

In [ ]:
# Creating Using Arrays.
df2 = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))
df2

# Empty Dataframe

In [ ]:
empty_df = pd.DataFrame()
empty_df

In [ ]:
empty_df['A'] = array
empty_df

In [ ]:
Matrix = np.array([[3,4,5],
                   [6,7,8],
                   [9,0,1]])

print(Matrix)
print("****************")

In [ ]:
df = pd.DataFrame(Matrix)
df

In [ ]:
df.columns

In [ ]:
df = pd.DataFrame(Matrix,columns=list('ABC'))
df

In [ ]:
df.columns

In [ ]:
list(df.columns)

# Creating by Index as well

In [ ]:
df = pd.DataFrame([[1, 2], [4, 5], [7, 8]],
                  index=['cobra', 'viper', 'sidewinder'],
                  columns=['max_speed', 'shield'])
df

In [ ]:
df.columns

In [ ]:
df.shape

# Manipulating Data

In [ ]:
df = pd.DataFrame(Matrix,columns=list('ABC'))
df

In [ ]:
df['D'] = [3,4,5]
df

In [ ]:
df['D'] = [0,0, 1]
df['e'] = 100
df

In [ ]:
df['F'] = np.random.randint(1,10,3)
df

In [ ]:
df['G'] = list('str')
df

In [ ]:
df['A'] = ["Balaji", "Amazing", "Teacher"]
df

In [ ]:
df['B'] = [["Balaji", "is"], ["an", "Amazing"], ["Teacher"]]
df

In [ ]:
df.dtypes

# Learning pandas with dataset

In [ ]:
import pandas as pd

In [ ]:
pd.read_

In [ ]:
df = pd.read_csv('Iris.csv') # Explain about iris dataset.
df

In [ ]:
type(df)

In [ ]:
df.index

In [ ]:
df.columns

In [ ]:
df.shape

In [ ]:
len(df.columns)

In [ ]:
list(df.columns)

In [ ]:
for i in df.columns:
    print(i)

In [ ]:
df.index, df.columns

In [ ]:
df.axes

In [ ]:
# Getting the shape of dataset.
df.shape

In [ ]:
df.index

In [ ]:
df.shape[0]

In [ ]:
 df.shape[1]

In [ ]:
# By default returns first 5 rows.
df.head()

In [ ]:
# By default returns first n rows.
df.head(10)

In [ ]:
# Gives last 5 records of dataframe.
df.tail()

In [ ]:
# Gives last records of dataframe.
df.tail(10)

In [ ]:
# Any random n samples
df.sample(10)

In [ ]:
# gives us the information of the table
df.info()

In [ ]:
# Only for numerical Calcualtions
df.describe()

# Slicing and Indexing

In [ ]:
df.head()

In [ ]:
# df[value_index:value_index-1]
df[2:5]

In [ ]:
df[0:1]

In [ ]:
df[20:30:2]

In [ ]:
df.columns

In [ ]:
type(df[['SepalLengthCm','SepalWidthCm']])

In [ ]:
df1 = df[['SepalLengthCm','SepalWidthCm']]

In [ ]:
df[['SepalLengthCm','SepalWidthCm']][0:4]

In [ ]:
df1[0:4]

In [ ]:
df[0:4][['SepalLengthCm','SepalWidthCm']]

In [ ]:
# 0:4:2 specifies a start index of 0, an end index of 4 (exclusive), and a step of 2.
df[0:4:2][['SepalLengthCm','SepalWidthCm']]

# Dropping in dataframes

In [ ]:
df = pd.read_csv('Iris.csv') # Explain about iris dataset.
df

In [ ]:
# Dropping columns by using names.
df_dropped_columns = df.drop(columns=['SepalWidthCm'])
df_dropped_columns

In [ ]:
df

In [ ]:
# Dropping rows by using indexes
df_dropped_rows = df.drop([0, 2])
df_dropped_rows

In [ ]:
# Modify the original Dataframe
df.drop(columns=['SepalWidthCm'], inplace=True)
df

In [ ]:
# Drop rows by index and modify the original DataFrame
df.drop([0, 2], inplace=True)
df

In [ ]:
df.drop(index=5, columns='PetalLengthCm', inplace=True)

In [ ]:
df

Be cautious with inplace=True as it modifies your data in place without the possibility of undoing the operation.

# Loc functions


Label based selecting methods.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('Iris.csv')
df

In [ ]:
df = pd.read_csv('Iris.csv')
# setting any column of df as index
df.set_index('Id',inplace=True)
df

In [ ]:
# syntax
df.loc[rows, columns] # Differentiating by comma

In [ ]:
# Loc uses actual values of index and columns
df.loc[:,:]

In [ ]:
df.loc[1]

In [ ]:
df[0:1]

In [ ]:
df.shape

In [ ]:
df.loc[13]

In [ ]:
df.columns

In [ ]:
df.loc[5,'SepalWidthCm'] # Throws error, as you need to give the name of column.

In [ ]:
df.loc[[3,5, 50, 100]]

In [ ]:
df1 = pd.read_csv('Iris.csv')
# setting any column of df as index
df1.set_index('SepalWidthCm',inplace=True)
df1

In [ ]:
df1.loc[3]

In [ ]:
df1

In [ ]:
df1.loc[[3,2.5]]

In [ ]:
df1.loc[2.5]

In [ ]:
df1.loc[[2.5],'PetalLengthCm' ]

In [ ]:
df

In [ ]:
df.loc[[3,5],['PetalLengthCm', 'SepalWidthCm'] ]

In [ ]:
df.loc[1:5]

In [ ]:
df.loc[1:5][['PetalLengthCm']]

In [ ]:
df

In [ ]:
df.loc[df['PetalLengthCm'] > 6]

In [ ]:
df.loc[df['PetalLengthCm'] > 6, ['SepalWidthCm']]

In [ ]:
df

In [ ]:
df.loc[(df['PetalLengthCm'] > 1) & (df['SepalLengthCm'] < 8)]

# iLoc functions

Index based data selecting method.

In [ ]:
# This is number based, not the actual values.

In [ ]:
df = pd.read_csv('Iris.csv')
# setting any column of df as index
df.set_index('SepalWidthCm',inplace=True)
df

In [ ]:
df1

In [ ]:
df1.iloc[0]

In [ ]:
df1.iloc[5]

In [ ]:
df.iloc[[0, 1]]

In [ ]:
df.iloc[:3]

In [ ]:
df.iloc[lambda x: x.index % 2 == 0]

In [ ]:
df.columns

In [ ]:
df.iloc[1:3, 0:3]

In [ ]:
df.iloc[1:5,1:4]

In [ ]:
df.head()

In [ ]:
df.iloc[2,2]

In [ ]:
df.iloc[2,2] = 100

In [ ]:
df.head()

In [ ]:
df

# Sorting Dataframes

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('Iris.csv')
df

In [ ]:
# Sorting in place
df.sort_index(inplace=True)
print("\nDataFrame after sorting by index in place:")
df

In [ ]:
df.sort_index(axis=0)

In [ ]:
df.sort_index(axis=0,ascending=False)

In [ ]:
# setting any column of df as index
df1 = df.set_index('SepalWidthCm')
df1

In [ ]:
df1.sort_index()

In [ ]:
df

In [ ]:
df.sort_index(axis=0)

In [ ]:
df.sort_index(axis=1)       # sorting the columns of the dataframe

In [ ]:
# Creating a DataFrame with unsorted column names
df = pd.DataFrame([[2, 1, 4], [5, 3, 6]], columns=['B', 'A', 'C'])
print("Original DataFrame:")
df

In [ ]:
# Sorting the DataFrame by its column labels
sorted_df = df.sort_index(axis=1)
print("\nDataFrame after sorting columns by name:")
sorted_df

In [ ]:
# Creating a MultiIndex DataFrame
index = pd.MultiIndex.from_tuples([('a', 1), ('b', 2), ('a', 2), ('b', 1)])
df_multi = pd.DataFrame({'A': [1, 2, 3, 4]}, index=index)
print("Original MultiIndex DataFrame:")
df_multi

In [ ]:
# Sorting by the first level of the index
sorted_multi = df_multi.sort_index(level=0)
print("\nMultiIndex DataFrame after sorting by the first level of index:")
sorted_multi

In [ ]:
# Sorting by the second level of the index
sorted_multi_level2 = df_multi.sort_index(level=1)
print("\nMultiIndex DataFrame after sorting by the second level of index:")
sorted_multi_level2

In [ ]:
df = pd.read_csv("Iris.csv")
df.shape

In [ ]:
df.T # Transpose of the dataframe. (rows becomes columns & columns into rows)

In [ ]:
(df.T).sort_index(axis=0, ascending=False)

In [ ]:
df = pd.read_csv("Iris.csv")
df.set_index('SepalWidthCm', inplace = True)
df.sort_index(inplace = True)
df

In [ ]:
# setting up default index columns
df.reset_index(inplace=True)
df

# Sorting by Column Values

In [ ]:
df = pd.read_csv('Iris.csv')
df

In [ ]:
df.sort_values('SepalLengthCm',ascending=True)

In [ ]:
df.sort_values(['PetalLengthCm','PetalWidthCm'],ascending=True)

In [ ]:
import pandas as pd

# Example DataFrame
data = {
    'PetalLengthCm': [1.4, 1.3, 1.5, 1.4],
    'PetalWidthCm': [0.2, 0.3, 0.2, 0.3],
    'Species': ['Setosa', 'Setosa', 'Setosa', 'Setosa']
}

df = pd.DataFrame(data)
df

In [ ]:
# Sorting by 'PetalLengthCm' primarily, then by 'PetalWidthCm'
sorted_df = df.sort_values(['PetalLengthCm', 'PetalWidthCm'], ascending=True)
sorted_df

In [ ]:
df.sort_values(['PetalLengthCm','PetalWidthCm'],ascending=[True,False])

In [ ]:
df.sort_values('Species',ascending=False)

# rearranging order of columns

In [ ]:
import pandas as pd

# Example DataFrame
df = pd.DataFrame({
    'B': [1, 2, 3],
    'A': [4, 5, 6],
    'C': [7, 8, 9]
})

print("Original DataFrame:")
df

In [ ]:
# Specifying the new order of columns
new_order = ['A', 'B', 'C']

In [ ]:
# Rearranging the columns
df_reordered = df[new_order]

print("DataFrame after rearranging columns:")
print(df_reordered)

In [ ]:
df

In [ ]:
df_reordered = df.reindex(['A', 'B', 'C'], axis=1)
df_reordered

In [ ]:
# Alphabetically
df_sorted = df[sorted(df.columns)]

# Custom sort (e.g., reverse alphabetical order)
df_custom_sorted = df[sorted(df.columns, reverse=True)]
df_custom_sorted

In [ ]:
df_reordered = df.loc[:, ['A', 'B', 'C']]
df_reordered

In [ ]:
# Assuming you know the positions of the columns you want to reorder
df_reordered = df.iloc[:, [1, 0, 2]]  # Here, 1, 0, 2 represents the new order of column indices
df_reordered

# Null value treatment

None or Null or np.nan values are treated as Null values.

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("Generated_Dataset.csv")

In [ ]:
df.shape

(1000, 8)

In [ ]:
df.head()

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City,Designation
0,97858,Ishaan_001,37.33,67.0,19.77,125979,Hyderabad,Clerk
1,22002,Rohan_002,24.59,69.0,11.83,131192,Kolkata,Clerk
2,40748,Shanaya_003,30.55,72.0,11.22,85875,Surat,Associate
3,34144,Aditi_004,51.88,80.0,11.83,110957,Delhi,Senior Manager
4,39603,Aditi_005,50.20,86.0,3.25,65751,Chennai,Executive

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Emp ID          1000 non-null   int64
 1   First Name      1000 non-null   object
 2   Age in Yrs      950 non-null    float64
 3   Weight in Kgs   922 non-null    float64
 4   Age in Company  1000 non-null   float64
 5   Salary          1000 non-null   int64
 6   City            1000 non-null   object
 7   Designation     1000 non-null   object
dtypes: float64(3), int64(2), object(3)
memory usage: 62.6+ KB

In [ ]:
df.isnull()

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City,Designation
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False

In [ ]:
import pandas as pd
import numpy as np

# Sample DataFrame with missing values
df1 = pd.DataFrame({'A': [1, np.nan, 3], 'B': [4, 5, np.nan]})

# Detecting missing values using isnull()
df1.isnull()

       A      B
0  False  False
1   True  False
2  False   True

In [ ]:
# Detecting missing values using isna()
df1.isna()

       A      B
0  False  False
1   True  False
2  False   True

In [ ]:
df.isna()

In [ ]:
df.isnull().sum()

Emp ID             0
First Name         0
Age in Yrs        50
Weight in Kgs     78
Age in Company     0
Salary             0
City               0
Designation        0
dtype: int64

In [ ]:
df.isna().sum()

In [ ]:
# Null value percentage
df.isnull().sum() * 100 / df.shape[0]

Emp ID            0.0
First Name        0.0
Age in Yrs        5.0
Weight in Kgs     7.8
Age in Company    0.0
Salary            0.0
City              0.0
Designation       0.0
dtype: float64

In [ ]:
for i,j in zip(df.columns, df.isnull().sum()):
    print(f"Percentage Null value in column {i} : {j*100/df.shape[0]} %", )

Percentage Null value in column Emp ID : 0.0 %
Percentage Null value in column First Name : 0.0 %
Percentage Null value in column Age in Yrs : 5.0 %
Percentage Null value in column Weight in Kgs : 7.8 %
Percentage Null value in column Age in Company : 0.0 %
Percentage Null value in column Salary : 0.0 %
Percentage Null value in column City : 0.0 %
Percentage Null value in column Designation : 0.0 %

In [ ]:
df.dropna() # deletes the entire rows wherever it finds null value

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City,Designation
0,97858,Ishaan_001,37.33,67.0,19.77,125979,Hyderabad,Clerk
1,22002,Rohan_002,24.59,69.0,11.83,131192,Kolkata,Clerk
2,40748,Shanaya_003,30.55,72.0,11.22,85875,Surat,Associate
3,34144,Aditi_004,51.88,80.0,11.83,110957,Delhi,Senior Manager
4,39603,Aditi_005,50.20,86.0,3.25,65751,Chennai,Executive
...,...,...,...,...,...,...,...,...
995,86657,Priya_996,29.38,69.0,9.87,152147,Surat,Analyst
996,27506,Priya_997,50.48,79.0,16.50,78720,Ahmedabad,Clerk
997,58006,Anika_998,51.56,59.0,28.19,141305,Chennai,Manager
998,97040,Aditi_999,45.27,72.0,9.50,66614,Kolkata,Manager
999,46670,Ishaan_1000,24.38,58.0,17.29,122448,Delhi,Associate

In [ ]:
df.shape

(1000, 8)

In [ ]:
df.dropna(inplace=True)
df

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City,Designation
0,97858,Ishaan_001,37.33,67.0,19.77,125979,Hyderabad,Clerk
1,22002,Rohan_002,24.59,69.0,11.83,131192,Kolkata,Clerk
2,40748,Shanaya_003,30.55,72.0,11.22,85875,Surat,Associate
3,34144,Aditi_004,51.88,80.0,11.83,110957,Delhi,Senior Manager
4,39603,Aditi_005,50.20,86.0,3.25,65751,Chennai,Executive
...,...,...,...,...,...,...,...,...
995,86657,Priya_996,29.38,69.0,9.87,152147,Surat,Analyst
996,27506,Priya_997,50.48,79.0,16.50,78720,Ahmedabad,Clerk
997,58006,Anika_998,51.56,59.0,28.19,141305,Chennai,Manager
998,97040,Aditi_999,45.27,72.0,9.50,66614,Kolkata,Manager
999,46670,Ishaan_1000,24.38,58.0,17.29,122448,Delhi,Associate

In [ ]:
df = pd.read_csv('Generated_Dataset.csv')
df

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City,Designation
0,97858,Ishaan_001,37.33,67.0,19.77,125979,Hyderabad,Clerk
1,22002,Rohan_002,24.59,69.0,11.83,131192,Kolkata,Clerk
2,40748,Shanaya_003,30.55,72.0,11.22,85875,Surat,Associate
3,34144,Aditi_004,51.88,80.0,11.83,110957,Delhi,Senior Manager
4,39603,Aditi_005,50.20,86.0,3.25,65751,Chennai,Executive
...,...,...,...,...,...,...,...,...
995,86657,Priya_996,29.38,69.0,9.87,152147,Surat,Analyst
996,27506,Priya_997,50.48,79.0,16.50,78720,Ahmedabad,Clerk
997,58006,Anika_998,51.56,59.0,28.19,141305,Chennai,Manager
998,97040,Aditi_999,45.27,72.0,9.50,66614,Kolkata,Manager
999,46670,Ishaan_1000,24.38,58.0,17.29,122448,Delhi,Associate

# Threshold Paramter in Dropping

In [ ]:
df.isna().sum()

In [ ]:
df

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City,Designation
0,97858,Ishaan_001,37.33,67.0,19.77,125979,Hyderabad,Clerk
1,22002,Rohan_002,24.59,69.0,11.83,131192,Kolkata,Clerk
2,40748,Shanaya_003,30.55,72.0,11.22,85875,Surat,Associate
3,34144,Aditi_004,51.88,80.0,11.83,110957,Delhi,Senior Manager
4,39603,Aditi_005,50.20,86.0,3.25,65751,Chennai,Executive
...,...,...,...,...,...,...,...,...
995,86657,Priya_996,29.38,69.0,9.87,152147,Surat,Analyst
996,27506,Priya_997,50.48,79.0,16.50,78720,Ahmedabad,Clerk
997,58006,Anika_998,51.56,59.0,28.19,141305,Chennai,Manager
998,97040,Aditi_999,45.27,72.0,9.50,66614,Kolkata,Manager
999,46670,Ishaan_1000,24.38,58.0,17.29,122448,Delhi,Associate

In [ ]:
df.dropna(thresh=5,axis=0)    # at least 6 columns should have non-null values otherwise drop that row.

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City,Designation
0,97858,Ishaan_001,37.33,67.0,19.77,125979,Hyderabad,Clerk
1,22002,Rohan_002,24.59,69.0,11.83,131192,Kolkata,Clerk
2,40748,Shanaya_003,30.55,72.0,11.22,85875,Surat,Associate
3,34144,Aditi_004,51.88,80.0,11.83,110957,Delhi,Senior Manager
4,39603,Aditi_005,50.20,86.0,3.25,65751,Chennai,Executive
...,...,...,...,...,...,...,...,...
995,86657,Priya_996,29.38,69.0,9.87,152147,Surat,Analyst
996,27506,Priya_997,50.48,79.0,16.50,78720,Ahmedabad,Clerk
997,58006,Anika_998,51.56,59.0,28.19,141305,Chennai,Manager
998,97040,Aditi_999,45.27,72.0,9.50,66614,Kolkata,Manager
999,46670,Ishaan_1000,24.38,58.0,17.29,122448,Delhi,Associate

In [ ]:
df.dropna()

# Subset Parameter

In [ ]:
df.dropna()

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City,Designation
0,97858,Ishaan_001,37.33,67.0,19.77,125979,Hyderabad,Clerk
1,22002,Rohan_002,24.59,69.0,11.83,131192,Kolkata,Clerk
2,40748,Shanaya_003,30.55,72.0,11.22,85875,Surat,Associate
3,34144,Aditi_004,51.88,80.0,11.83,110957,Delhi,Senior Manager
4,39603,Aditi_005,50.20,86.0,3.25,65751,Chennai,Executive
...,...,...,...,...,...,...,...,...
995,86657,Priya_996,29.38,69.0,9.87,152147,Surat,Analyst
996,27506,Priya_997,50.48,79.0,16.50,78720,Ahmedabad,Clerk
997,58006,Anika_998,51.56,59.0,28.19,141305,Chennai,Manager
998,97040,Aditi_999,45.27,72.0,9.50,66614,Kolkata,Manager
999,46670,Ishaan_1000,24.38,58.0,17.29,122448,Delhi,Associate

In [ ]:
df.dropna(subset=['Weight in Kgs'])

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City,Designation
0,97858,Ishaan_001,37.33,67.0,19.77,125979,Hyderabad,Clerk
1,22002,Rohan_002,24.59,69.0,11.83,131192,Kolkata,Clerk
2,40748,Shanaya_003,30.55,72.0,11.22,85875,Surat,Associate
3,34144,Aditi_004,51.88,80.0,11.83,110957,Delhi,Senior Manager
4,39603,Aditi_005,50.20,86.0,3.25,65751,Chennai,Executive
...,...,...,...,...,...,...,...,...
995,86657,Priya_996,29.38,69.0,9.87,152147,Surat,Analyst
996,27506,Priya_997,50.48,79.0,16.50,78720,Ahmedabad,Clerk
997,58006,Anika_998,51.56,59.0,28.19,141305,Chennai,Manager
998,97040,Aditi_999,45.27,72.0,9.50,66614,Kolkata,Manager
999,46670,Ishaan_1000,24.38,58.0,17.29,122448,Delhi,Associate

In [ ]:
df.dropna(subset=['Weight in Kgs']).isna().sum()

Emp ID             0
First Name         0
Age in Yrs        46
Weight in Kgs      0
Age in Company     0
Salary             0
City               0
Designation        0
dtype: int64

In [ ]:
df.dropna(subset=['City'])

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City,Designation
0,97858,Ishaan_001,37.33,67.0,19.77,125979,Hyderabad,Clerk
1,22002,Rohan_002,24.59,69.0,11.83,131192,Kolkata,Clerk
2,40748,Shanaya_003,30.55,72.0,11.22,85875,Surat,Associate
3,34144,Aditi_004,51.88,80.0,11.83,110957,Delhi,Senior Manager
4,39603,Aditi_005,50.20,86.0,3.25,65751,Chennai,Executive
...,...,...,...,...,...,...,...,...
995,86657,Priya_996,29.38,69.0,9.87,152147,Surat,Analyst
996,27506,Priya_997,50.48,79.0,16.50,78720,Ahmedabad,Clerk
997,58006,Anika_998,51.56,59.0,28.19,141305,Chennai,Manager
998,97040,Aditi_999,45.27,72.0,9.50,66614,Kolkata,Manager
999,46670,Ishaan_1000,24.38,58.0,17.29,122448,Delhi,Associate

In [ ]:
df.shape

(1000, 8)

In [ ]:
df.dropna(subset=['City','Age in Yrs'])

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City,Designation
0,97858,Ishaan_001,37.33,67.0,19.77,125979,Hyderabad,Clerk
1,22002,Rohan_002,24.59,69.0,11.83,131192,Kolkata,Clerk
2,40748,Shanaya_003,30.55,72.0,11.22,85875,Surat,Associate
3,34144,Aditi_004,51.88,80.0,11.83,110957,Delhi,Senior Manager
4,39603,Aditi_005,50.20,86.0,3.25,65751,Chennai,Executive
...,...,...,...,...,...,...,...,...
995,86657,Priya_996,29.38,69.0,9.87,152147,Surat,Analyst
996,27506,Priya_997,50.48,79.0,16.50,78720,Ahmedabad,Clerk
997,58006,Anika_998,51.56,59.0,28.19,141305,Chennai,Manager
998,97040,Aditi_999,45.27,72.0,9.50,66614,Kolkata,Manager
999,46670,Ishaan_1000,24.38,58.0,17.29,122448,Delhi,Associate

In [ ]:
df.dropna(subset=['City','Age in Yrs']).isna().sum()

Emp ID             0
First Name         0
Age in Yrs         0
Weight in Kgs     74
Age in Company     0
Salary             0
City               0
Designation        0
dtype: int64

In [ ]:
df.dropna(subset=['City','Age in Yrs', 'Weight in Kgs']).isna().sum()

Emp ID            0
First Name        0
Age in Yrs        0
Weight in Kgs     0
Age in Company    0
Salary            0
City              0
Designation       0
dtype: int64

Determine if row or column is removed from DataFrame, when we have at least one NA or all NA.

1. â€˜anyâ€™ : If any NA values are present, drop that row or column.

2. â€˜allâ€™ : If all values are NA, drop that row or column.

In [ ]:
df

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City,Designation
0,97858,Ishaan_001,37.33,67.0,19.77,125979,Hyderabad,Clerk
1,22002,Rohan_002,24.59,69.0,11.83,131192,Kolkata,Clerk
2,40748,Shanaya_003,30.55,72.0,11.22,85875,Surat,Associate
3,34144,Aditi_004,51.88,80.0,11.83,110957,Delhi,Senior Manager
4,39603,Aditi_005,50.20,86.0,3.25,65751,Chennai,Executive
...,...,...,...,...,...,...,...,...
995,86657,Priya_996,29.38,69.0,9.87,152147,Surat,Analyst
996,27506,Priya_997,50.48,79.0,16.50,78720,Ahmedabad,Clerk
997,58006,Anika_998,51.56,59.0,28.19,141305,Chennai,Manager
998,97040,Aditi_999,45.27,72.0,9.50,66614,Kolkata,Manager
999,46670,Ishaan_1000,24.38,58.0,17.29,122448,Delhi,Associate

In [ ]:
df.dropna(subset=['City','Age in Company'],how='all')

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City,Designation
0,97858,Ishaan_001,37.33,67.0,19.77,125979,Hyderabad,Clerk
1,22002,Rohan_002,24.59,69.0,11.83,131192,Kolkata,Clerk
2,40748,Shanaya_003,30.55,72.0,11.22,85875,Surat,Associate
3,34144,Aditi_004,51.88,80.0,11.83,110957,Delhi,Senior Manager
4,39603,Aditi_005,50.20,86.0,3.25,65751,Chennai,Executive
...,...,...,...,...,...,...,...,...
995,86657,Priya_996,29.38,69.0,9.87,152147,Surat,Analyst
996,27506,Priya_997,50.48,79.0,16.50,78720,Ahmedabad,Clerk
997,58006,Anika_998,51.56,59.0,28.19,141305,Chennai,Manager
998,97040,Aditi_999,45.27,72.0,9.50,66614,Kolkata,Manager
999,46670,Ishaan_1000,24.38,58.0,17.29,122448,Delhi,Associate

In [ ]:
df.dropna(subset=['City','Weight in Kgs'],how='any')

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City,Designation
0,97858,Ishaan_001,37.33,67.0,19.77,125979,Hyderabad,Clerk
1,22002,Rohan_002,24.59,69.0,11.83,131192,Kolkata,Clerk
2,40748,Shanaya_003,30.55,72.0,11.22,85875,Surat,Associate
3,34144,Aditi_004,51.88,80.0,11.83,110957,Delhi,Senior Manager
4,39603,Aditi_005,50.20,86.0,3.25,65751,Chennai,Executive
...,...,...,...,...,...,...,...,...
995,86657,Priya_996,29.38,69.0,9.87,152147,Surat,Analyst
996,27506,Priya_997,50.48,79.0,16.50,78720,Ahmedabad,Clerk
997,58006,Anika_998,51.56,59.0,28.19,141305,Chennai,Manager
998,97040,Aditi_999,45.27,72.0,9.50,66614,Kolkata,Manager
999,46670,Ishaan_1000,24.38,58.0,17.29,122448,Delhi,Associate

# Finding Index of the records where it is null

In [ ]:
df.isna()

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City,Designation
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False

In [ ]:
np.where(df.isna())

(array([ 21,  28,  34,  35,  44,  77,  81,  84,  89,  92,  93,  97, 106,
        107, 120, 126, 129, 129, 148, 156, 165, 181, 187, 192, 193, 204,
        219, 224, 227, 237, 247, 269, 278, 286, 287, 291, 293, 294, 299,
        314, 321, 322, 324, 359, 373, 378, 388, 391, 395, 405, 409, 426,
        426, 435, 442, 448, 466, 474, 496, 512, 514, 522, 530, 532, 534,
        534, 539, 543, 550, 552, 555, 556, 561, 563, 566, 566, 572, 573,
        576, 577, 578, 600, 603, 604, 605, 615, 616, 636, 641, 643, 647,
        684, 688, 701, 717, 720, 744, 745, 749, 755, 758, 768, 793, 797,
        809, 812, 814, 815, 828, 865, 871, 875, 880, 894, 898, 901, 910,
        915, 929, 942, 948, 949, 950, 951, 956, 968, 977, 985]),
 array([3, 3, 3, 2, 2, 3, 3, 3, 2, 2, 3, 2, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3,
        3, 2, 3, 3, 3, 2, 3, 3, 2, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 2, 2, 3, 2, 3, 2, 2, 3, 3, 2, 3, 3, 2, 3, 2, 2, 2, 3, 3, 2, 3,
        2, 3, 2, 2, 3, 2, 3, 3, 2, 3, 2, 3, 2, 2, 3, 2, 2, 3, 2, 3, 3, 2,
        2, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 2, 3, 3, 2, 2, 3, 2, 2, 3, 3, 3,
        2, 2, 3, 3, 3, 2, 2, 2, 2, 3, 2, 3, 2, 3, 2, 3, 3, 2]))

In [ ]:
df.columns

Index(['Emp ID', 'First Name', 'Age in Yrs', 'Weight in Kgs', 'Age in Company',
       'Salary', 'City', 'Designation'],
      dtype='object')

In [ ]:
df.loc[977]

Emp ID                83970
First Name        Priya_978
Age in Yrs            29.87
Weight in Kgs           NaN
Age in Company         14.8
Salary               139797
City              Hyderabad
Designation         Manager
Name: 977, dtype: object

In [ ]:
df.loc[21,'Weight in Kgs']

nan

In [ ]:
df.loc[21,'Weight in Kgs'] = 30

In [ ]:
df.loc[21,'Weight in Kgs']

30.0

In [ ]:
np.where(df['Age in Company'].isnull())

(array([], dtype=int64),)

# Filter dataset only for Null Values

In [ ]:
df[df['Weight in Kgs'].isna()]

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City,Designation
28,53132,Anika_029,42.20,NaN,9.99,148151,Hyderabad,Senior Manager
34,98956,Anika_035,35.07,NaN,9.06,86528,Surat,Executive
77,21305,Anika_078,23.81,NaN,2.05,56838,Bangalore,Associate
81,99731,Priya_082,47.34,NaN,14.27,106166,Mumbai,Senior Manager
84,49194,Ishaan_085,26.00,NaN,1.35,115630,Mumbai,Manager
...,...,...,...,...,...,...,...,...
942,95256,Anika_943,34.84,NaN,6.23,78448,Delhi,Senior Manager
949,73893,Ishaan_950,45.69,NaN,10.81,82802,Jaipur,Senior Manager
951,53795,Vivaan_952,24.25,NaN,23.25,56418,Hyderabad,Executive
968,75042,Aarav_969,42.31,NaN,15.10,70183,Bangalore,Senior Manager
977,83970,Priya_978,29.87,NaN,14.80,139797,Hyderabad,Manager

# Fixing Null Values

In [ ]:
import pandas as pd
import numpy as np

# Creating a small dummy DataFrame with null values
np.random.seed(0)  # For reproducible output
data = {
    'A': [1, 2, np.nan, 4, 5, np.nan, 7, 8, 9, 10],
    'B': [np.nan, 1, 2, 3, 4, 5, np.nan, 7, 8, 9],
    'C': [2, 3, 4, np.nan, np.nan, np.nan, 7, 8, 9, 10],
    'D': ['x', np.nan, 'y', 'x', 'y', 'x', np.nan, 'y', 'x', 'y']
}

df = pd.DataFrame(data)

# Display the original DataFrame
print("Original DataFrame:")
df

Original DataFrame:

      A    B     C    D
0   1.0  NaN   2.0    x
1   2.0  1.0   3.0  NaN
2   NaN  2.0   4.0    y
3   4.0  3.0   NaN    x
4   5.0  4.0   NaN    y
5   NaN  5.0   NaN    x
6   7.0  NaN   7.0  NaN
7   8.0  7.0   8.0    y
8   9.0  8.0   9.0    x
9  10.0  9.0  10.0    y

In [ ]:
|# Dropping all values of Null in df
df.dropna()  # Drops rows with any null values

      A    B     C  D
7   8.0  7.0   8.0  y
8   9.0  8.0   9.0  x
9  10.0  9.0  10.0  y

In [ ]:
df.dropna(how='any')  # Drops rows where all values are null

      A    B     C  D
7   8.0  7.0   8.0  y
8   9.0  8.0   9.0  x
9  10.0  9.0  10.0  y

In [ ]:
# Drop columns with any null values
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# Fill with a specific value
df.fillna(0)

      A    B     C  D
0   1.0  0.0   2.0  x
1   2.0  1.0   3.0  0
2   0.0  2.0   4.0  y
3   4.0  3.0   0.0  x
4   5.0  4.0   0.0  y
5   0.0  5.0   0.0  x
6   7.0  0.0   7.0  0
7   8.0  7.0   8.0  y
8   9.0  8.0   9.0  x
9  10.0  9.0  10.0  y

In [ ]:
# Fill with mean for numeric columns
df.fillna(df.mean())

<ipython-input-72-6d2178581ba3>:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.fillna(df.mean())

       A      B          C    D
0   1.00  4.875   2.000000    x
1   2.00  1.000   3.000000  NaN
2   5.75  2.000   4.000000    y
3   4.00  3.000   6.142857    x
4   5.00  4.000   6.142857    y
5   5.75  5.000   6.142857    x
6   7.00  4.875   7.000000  NaN
7   8.00  7.000   8.000000    y
8   9.00  8.000   9.000000    x
9  10.00  9.000  10.000000    y

In [ ]:
df.columns

Index(['A', 'C'], dtype='object')

In [ ]:
df

      A    B     C    D
0   1.0  NaN   2.0    x
1   2.0  1.0   3.0  NaN
2   NaN  2.0   4.0    y
3   4.0  3.0   NaN    x
4   5.0  4.0   NaN    y
5   NaN  5.0   NaN    x
6   7.0  NaN   7.0  NaN
7   8.0  7.0   8.0    y
8   9.0  8.0   9.0    x
9  10.0  9.0  10.0    y

In [ ]:
# Correctly fill NaN values in columns 'A' and 'C' with 0
df[['A', 'C']] = df[['A', 'C']].fillna(0)

# Fill NaN values in column 'B' with its own mean
df['B'] = df['B'].fillna(df['B'].mean())

# Fill NaN values in column 'D' with its mode
# This assumes df['D'].mode()[0] does not result in an empty series; otherwise, you should handle that case.
df['D'] = df['D'].fillna(df['D'].mode()[0])

df

      A      B     C  D
0   1.0  4.875   2.0  x
1   2.0  1.000   3.0  x
2   0.0  2.000   4.0  y
3   4.0  3.000   0.0  x
4   5.0  4.000   0.0  y
5   0.0  5.000   0.0  x
6   7.0  4.875   7.0  x
7   8.0  7.000   8.0  y
8   9.0  8.000   9.0  x
9  10.0  9.000  10.0  y

In [ ]:
# Fill categorical data with the mode
df.fillna(df['D'].mode()[0])

      A    B     C  D
0   1.0    x   2.0  x
1   2.0  1.0   3.0  x
2     x  2.0   4.0  y
3   4.0  3.0     x  x
4   5.0  4.0     x  y
5     x  5.0     x  x
6   7.0    x   7.0  x
7   8.0  7.0   8.0  y
8   9.0  8.0   9.0  x
9  10.0  9.0  10.0  y

# Group By In DataFrames

In [ ]:
import pandas as pd

# Creating the first DataFrame: Orders
data1 = {
    'OrderID': [1, 2, 3],
    'CustomerName': ['Alice', 'Bob', 'Charlie']
}
df1 = pd.DataFrame(data1)

print(df1)

# Creating the second DataFrame: Items in Orders
data2 = {
    'OrderID': [1, 1, 2, 2, 3, 3, 3],
    'ItemName': ['ItemA', 'ItemB', 'ItemB', 'ItemC', 'ItemA', 'ItemB', 'ItemC']
}
df2 = pd.DataFrame(data2)

print(df2)

# Performing an inner join on the 'OrderID' column
result = pd.merge(df1, df2, on='OrderID')

print(result)